name: ci
on: [ push, pull_request ]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: detekt
        run: |
          ./gradlew detektAll
      - name: ktlint
        run: |
          ./gradlew ktlintCheck
  cd-snapshot:
    runs-on: macos-latest
    needs: ci
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: publish snapshot sonatype
        run: |
          bash scripts/deploy-sonatype.sh
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
  cd-release:
    runs-on: macos-latest
    needs: ci
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: little-core-labs/get-git-tag@v3.0.2
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
      - name: publish release sonatype
        run: |
          bash scripts/deploy-sonatype.sh
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
